version: '3.9'

services:
  postgres_todo:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${IMAGE_POSTGRES}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - "${EXTERNAL_PORT_POSTGRES}:${INTERNAL_PORT_POSTGRES}"
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    networks:
      - todo_network

  pgadmin_todo:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: ${IMAGE_PGADMIN}
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - postgres_todo
    networks:
      - todo_network

  redisstack_todo:
    container_name: ${REDISSTACK_CONTAINER_NAME}
    image: ${IMAGE_REDISSTACK}
    restart: always
    volumes:
      - ${REDISSTACK_DATA}:/data
      - ${REDISSTACK_DATA_INSIGHT}:/db
    ports:
      - ${EXTERNAL_PORT_REDIS}:${INTERNAL_PORT_REDIS}
      - ${EXTERNAL_PORT_UI_REDIS}:${INTERNAL_PORT_UI_REDIS}
    networks:
      - todo_network
 
  fastapi_todo:
    build: .
    container_name: ${FASTAPI_CONTAINER_NAME}
    command: 
      [
        "uvicorn", 
        "--factory", "app:create_app", 
        "--reload", 
        "--host", "0.0.0.0", 
        "--port", "8000"
      ] 
    restart: always
    volumes:
      - .:/code
    ports:
      - "${EXTERNAL_PORT_FASTAPI}:${INTERNAL_PORT_FASTAPI}"
    networks:
      - todo_network
    depends_on:
      - postgres_todo
      - pgadmin_todo
      - redisstack_todo


networks:
  todo_network:  
    external: true