version: '3.9'

services:
  postgres_todo:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${IMAGE_POSTGRES}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - "${EXTERNAL_PORT_POSTGRES}:${INTERNAL_PORT_POSTGRES}"
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    networks:
      - todo_network

  pgadmin_todo:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: ${IMAGE_PGADMIN}
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - postgres_todo
    networks:
      - todo_network

  redisstack_todo:
    container_name: ${REDISSTACK_CONTAINER_NAME}
    image: ${IMAGE_REDISSTACK}
    restart: always
    volumes:
      - ${REDISSTACK_DATA}:/data
      - ${REDISSTACK_DATA_INSIGHT}:/db
    ports:
      - ${EXTERNAL_PORT_REDIS}:${INTERNAL_PORT_REDIS}
      - ${EXTERNAL_PORT_UI_REDIS}:${INTERNAL_PORT_UI_REDIS}
    networks:
      - todo_network
  
  miniotodo:
    container_name: ${MINIO_CONTAINER_NAME}
    image: minio/minio
    restart: always
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_PROMETHEUS_AUTH_TYPE=${MINIO_PROMETHEUS_AUTH_TYPE}
      - MINIO_CACHE=${MINIO_CACHE}
      - MINIO_CACHE_DRIVES=${MINIO_CACHE_DRIVES}
      - MINIO_CACHE_QUOTA=${MINIO_CACHE_QUOTA}
      - MINIO_CACHE_AFTER=${MINIO_CACHE_AFTER}
      - MINIO_CACHE_WATERMARK_LOW=${MINIO_CACHE_WATERMARK_LOW}
      - MINIO_CACHE_WATERMARK_HIGH=${MINIO_CACHE_WATERMARK_HIGH}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":${INTERNAL_PORT_CONSOLE_MINIO}" /data${MINIO_DATA_SET_COUNT}
    ports:
      - "${EXTERNAL_PORT_MINIO}:${INTERNAL_PORT_MINIO}"
      - "${EXTERNAL_PORT_CONSOLE_MINIO}:${INTERNAL_PORT_CONSOLE_MINIO}"
    volumes: 
      - ${MINIO_DATA_SET1}:/data1
      - ${MINIO_DATA_SET2}:/data2
      - ${MINIO_DATA_SET3}:/data3
      - ${MINIO_DATA_SET4}:/data4
    networks:
      - todo_network
    depends_on:
      - postgres_todo

  fastapi_todo:
    build: .
    container_name: ${FASTAPI_CONTAINER_NAME}
    command: 
      [
        "uvicorn", 
        "--factory", "app:create_app", 
        "--reload", 
        "--host", "0.0.0.0", 
        "--port", "8000"
      ] 
    restart: always
    volumes:
      - .:/code
    ports:
      - "${EXTERNAL_PORT_FASTAPI}:${INTERNAL_PORT_FASTAPI}"
    networks:
      - todo_network
    depends_on:
      - postgres_todo
      - pgadmin_todo
      - redisstack_todo
      - miniotodo

  
networks:
  todo_network:  
    external: true